#!/bin/bash
APP="jeeves-chatbot-testing "
VAR_CONFIG_COMMAND="heroku config:set --app "

echo Current application: $APP

$VAR_CONFIG_COMMAND $APP HUBOT_ADAPTER=groupme
$VAR_CONFIG_COMMAND $APP HUBOT_ALIAS=/
$VAR_CONFIG_COMMAND $APP HUBOT_GROUPME_BOT_ID=4e06098e11bbe85170702c5fd8
$VAR_CONFIG_COMMAND $APP HUBOT_GROUPME_ROOM_ID=15600682
$VAR_CONFIG_COMMAND $APP HUBOT_GROUPME_TOKEN=Exa0e7vaEPMi0lfh7SNz8nfHQNJ38i9b86qZ7kGP
$VAR_CONFIG_COMMAND $APP HUBOT_HEROKU_KEEPALIVE_URL=https://jeeves-chatbot-testing.herokuapp.com/
$VAR_CONFIG_COMMAND $APP HUBOT_HEROKU_SLEEP_TIME=24:00
$VAR_CONFIG_COMMAND $APP HUBOT_HEROKU_WAKEUP_TIME=6:00
$VAR_CONFIG_COMMAND $APP HUBOT_YOUTUBE_API_KEY=AIzaSyApoFAXmCMGFSAIb65NcJJz-dw-XLxNdxg
$VAR_CONFIG_COMMAND $APP HUBOT_YOUTUBE_DETERMINISTIC_RESULTS=true
$VAR_CONFIG_COMMAND $APP TZ=America/Los_Angeles
